INSERT INTO [dbo].[CatalogoDominio] VALUES(101, 'ModalidadeExecucao', 'Presencial', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(102, 'ModalidadeExecucao', 'Teletrabalho Parcial', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(103, 'ModalidadeExecucao', 'Teletrabalho Integral', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(201, 'FormaCalculoTempoItemCatalogo', 'Alocação diária', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(202, 'FormaCalculoTempoItemCatalogo', 'Por atividade', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(301, 'SituacaoPlanoTrabalho', 'Rascunho', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(307, 'SituacaoPlanoTrabalho', 'Habilitação', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(309, 'SituacaoPlanoTrabalho', 'Em execução', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(310, 'SituacaoPlanoTrabalho', 'Executado', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(311, 'SituacaoPlanoTrabalho', 'Concluído', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(401, 'SituacaoPactoTrabalho', 'Rascunho', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(402, 'SituacaoPactoTrabalho', 'Enviado para aceite', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(403, 'SituacaoPactoTrabalho', 'Aceito', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(404, 'SituacaoPactoTrabalho', 'Rejeitado', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(405, 'SituacaoPactoTrabalho', 'Em execução', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(406, 'SituacaoPactoTrabalho', 'Executado', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(407, 'SituacaoPactoTrabalho', 'Concluído', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(501, 'SituacaoAtividadePactoTrabalho', 'Programada', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(502, 'SituacaoAtividadePactoTrabalho', 'Em execução', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(503, 'SituacaoAtividadePactoTrabalho', 'Concluída', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(601, 'TipoSolicitacaoPactoTrabalho', 'Nova atividade', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(602, 'TipoSolicitacaoPactoTrabalho', 'Alteração prazo', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(603, 'TipoSolicitacaoPactoTrabalho', 'Prazo de atividade ultrapassado', 1)
insert into [dbo].[CatalogoDominio] values(604, 'TipoSolicitacaoPactoTrabalho', 'Excluir atividade', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(701, 'TipoRespostaQuestionario', 'Texto livre', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(702, 'TipoRespostaQuestionario', 'Decimal', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(703, 'TipoRespostaQuestionario', 'Inteiro', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(801, 'SituacaoPlanoTrabalhoCandidatura', 'Solicitada', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(802, 'SituacaoPlanoTrabalhoCandidatura', 'Legalidade rejeitada', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(803, 'SituacaoPlanoTrabalhoCandidatura', 'Legalidade verificada', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(804, 'SituacaoPlanoTrabalhoCandidatura', 'Aprovada', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(805, 'SituacaoPlanoTrabalhoCandidatura', 'Rejeitada', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(901, 'CriterioPerfilAtividadePlano', 'Capacidade de organização e autodisciplina', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(902, 'CriterioPerfilAtividadePlano', 'Capacidade de cumprimento das atividades nos prazos acordados', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(903, 'CriterioPerfilAtividadePlano', 'Capacidade de interação com a equipe', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(904, 'CriterioPerfilAtividadePlano', 'Atuação tempestiva', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(905, 'CriterioPerfilAtividadePlano', 'Pró-atividade na resolução de problemas', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(906, 'CriterioPerfilAtividadePlano', 'Abertura para utilização de novas tecnologias', 1)
INSERT INTO [dbo].[CatalogoDominio] VALUES(907, 'CriterioPerfilAtividadePlano', 'Orientação para resultados', 1)





INSERT INTO [dbo].[UF] VALUES ('AC', 'ACRE')
INSERT INTO [dbo].[UF] VALUES ('AL', 'ALAGOAS')
INSERT INTO [dbo].[UF] VALUES ('AP', 'AMAPÁ')
INSERT INTO [dbo].[UF] VALUES ('AM', 'AMAZONAS')
INSERT INTO [dbo].[UF] VALUES ('BA', 'BAHIA')
INSERT INTO [dbo].[UF] VALUES ('CE', 'CEARÁ')
INSERT INTO [dbo].[UF] VALUES ('DF', 'DISTRITO FEDERAL')
INSERT INTO [dbo].[UF] VALUES ('ES', 'ESPIRITO SANTO')
INSERT INTO [dbo].[UF] VALUES ('GO', 'GOIAS')
INSERT INTO [dbo].[UF] VALUES ('MA', 'MARANHAO')
INSERT INTO [dbo].[UF] VALUES ('MT', 'MATO GROSSO')
INSERT INTO [dbo].[UF] VALUES ('MS', 'MATO GROSSO DO SUL')
INSERT INTO [dbo].[UF] VALUES ('MG', 'MINAS GERAIS')
INSERT INTO [dbo].[UF] VALUES ('PA', 'PARA')
INSERT INTO [dbo].[UF] VALUES ('PB', 'PARAIBA')
INSERT INTO [dbo].[UF] VALUES ('PR', 'PARANA')
INSERT INTO [dbo].[UF] VALUES ('PE', 'PERNAMBUCO')
INSERT INTO [dbo].[UF] VALUES ('PI', 'PIAUI')
INSERT INTO [dbo].[UF] VALUES ('RJ', 'RIO DE JANEIRO')
INSERT INTO [dbo].[UF] VALUES ('RN', 'RIO GRANDE DO NORTE')
INSERT INTO [dbo].[UF] VALUES ('RS', 'RIO GRANDE DO SUL')
INSERT INTO [dbo].[UF] VALUES ('RO', 'RONDONIA')
INSERT INTO [dbo].[UF] VALUES ('RR', 'RORAIMA')
INSERT INTO [dbo].[UF] VALUES ('SC', 'SANTA CATARINA')
INSERT INTO [dbo].[UF] VALUES ('SP', 'SAO PAULO')
INSERT INTO [dbo].[UF] VALUES ('SE', 'SERGIPE')
INSERT INTO [dbo].[UF] VALUES ('TO', 'TOCANTINS')
